In [1]:
import pandas as pd
import numpy

In [2]:
mock_file = pd.read_csv('sales by member detail 2013-2015 QB.csv')

In [3]:
mock_file = mock_file[mock_file.Num > 0]
mock_file

,Name,Date,Transaction Type,Num,Product/Service,Memo/Description,Qty,Rate,Amount,Balance
1,Lethargy Network,11/07/2013,Sales Receipt,1100,Special Events Income:Special Events Contribut...,Special Events Contributions,1,635,635,635
2,Lethargy Network,11/07/2013,Sales Receipt,1100,2016 Membership Dues,NaN,1,1,1,636
5,"Adze, Anne & Spence",12/28/2013,Sales Receipt,1148,Program Income:Membership Dues:E 250 Old Friends,Annual Membership - Old Friends,1,250,250,250
8,Minnesota Capital LLC,10/06/14,Sales Receipt,1334,Special Events Income:Special Events Sponsors:...,Osprey Sponsor,1,500,500,500
11,Minnesota Coastal Heritage Trust,05/01/2015,Sales Receipt,1305,Direct Public Support:Corporate Contributions,Corporate Contributions,1,250,250,250
14,"Ball, Lucille",02/24/2015,Sales Receipt,1179,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
15,"Ball, Lucille",04/09/2015,Sales Receipt,1262,Special Events Income:Special Events Sponsors:...,NaN,1,40,40,65
18,Lamar Odom,02/24/2015,Sales Receipt,1171,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
21,"Andreas, Emily",10/28/2013,Sales Receipt,1086,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
24,Andra Self Bruce,10/24/2013,Sales Receipt,1030,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15
25,Andra Self Bruce,02/24/2015,Sales Receipt,1218,Special Events Income:The Great Escape,NaN,1,25,25,40
28,Rick Rangel,05/21/2014,Sales Receipt,1162,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
31,"Ambuehl Jackson, LLP",10/55/14,Sales Receipt,1338,Special Events Income:Special Events Sponsors:...,Silver Level Sponsor,1,250,250,250
34,"Ambuehl, Conrad & Gigi",10/06/14,Sales Receipt,1333,Special Events Income:Special Events Sponsors:...,Individual Sponsor,1,250,250,250
37,"Ash, Susan Jones",11/12/2013,Sales Receipt,1112,Program Income:Membership Dues:D 100 Friend,Annual Membership - Friend,1,100,100,100
40,"asher, darryl",02/24/2015,Sales Receipt,1186,Special Events Income:The Great Escape,NaN,1,40,40,40
43,"asher, James",02/24/2015,Sales Receipt,1247,Special Events Income:The Great Escape,NaN,1,20,20,20
46,Barbara hayes,02/24/2015,Sales Receipt,1200,Special Events Income:The Great Escape,NaN,1,40,40,40
49,"Barnett, David & Mary",10/28/2013,Sales Receipt,1144,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
52,"Bell, Angela",02/24/2015,Sales Receipt,1225,Special Events Income:The Great Escape,NaN,1,40,40,40
55,"Bender-Fayette, David L",04/17/2015,Sales Receipt,1285,Special Events Income:Special Events Sponsors:...,NaN,1,250,250,250
58,"Bender-Fayette, Thomas & Dina",11/04/2013,Sales Receipt,1118,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
61,"Bense, Leroy & Aurelia",11/13/2013,Sales Receipt,1165,Program Income:Membership Dues:B 50 High-Fiver,14 Annual Membership - High-Fiver,1,50,50,50
64,Billy R Cyrus,12/28/2013,Sales Receipt,1152,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
67,EKG & Co. INC.,10/03/14,Sales Receipt,1327,Special Events Income:Special Events Sponsors:...,Osprey Sponsor,1,500,500,500
70,"Black, Peggy",02/24/2015,Sales Receipt,1213,Special Events Income:The Great Escape,NaN,1,20,20,20
73,"Blackburn, James",10/19/2013,Sales Receipt,1044,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15
76,"Blount, Russell",02/24/2015,Sales Receipt,1224,Special Events Income:The Great Escape,NaN,1,35,35,35
79,Dockenstette,02/24/2015,Sales Receipt,1204,Special Events Income:The Great Escape,NaN,1,55,55,55
82,"Bolson, Barry",01/08/2015,Sales Receipt,1299,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
...,...,...,...,...,...,...,...,...,...,...
370,"Raddick, Charlie & Corinne",10/21/14,Sales Receipt,1353,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
373,"Grant, Bernadette",05/21/14,Sales Receipt,1155,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
376,"Green, E Hamilton",10/25/2013,Sales Receipt,1062,Program Income:Membership Dues:D 100 Friend,14 Annual Membership - Friend,1,100,100,100
377,"Green, E Hamilton",10/21/14,Sales Receipt,1296,Program Income:Membership Dues:D 100 Friend,Annual Membership - Friend,1,100,100,200
380,Chuck M Yeager,10/22/2013,Sales Receipt,1037,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15
381,Chuck M Yeager,10/26/2013,Sales Receipt,1053,Special Events Income:Special Events Contribut...,GC Entry Fee Day of Race Adult,1,20,20,35
384,MinnesotaCoast Resource Cnservation & Develpme...,05/02/14,Sales Receipt,1004,Direct Public Grants:Foundations and Trusts,Trap the Trash Project,1,0,0,0
387,"Backbarth Delivery Service, Inc.",10/06/14,Sales Receipt,1332,Special Events Income:Special Events Sponsors:...,River Otter Sponsor,1,1000,1000,1000
390,"Shaefer, Susan & Jay",11/05/2013,Sales Receipt,1120,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,50
393,"Shatner, Walter & Stephanie",01/08/2015,Sales Receipt,1304,Program Income:Membership Dues:C 75 Frienderton,Annual Membership - Frienderton,1,75,75,75
396,"Famil, Jubal & Tray",11/17/14,Sales Receipt,1288,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,50
399,Hancock Bank,10/06/14,Sales Receipt,1331,Special Events Income:Special Events Sponsors:...,Individual Sponsor,1,250,250,250
402,"Hanley, Stewart",02/24/2015,Sales Receipt,1174,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
405,"Shanna, Nancy & Mike",12/31/2013,Sales Receipt,1139,Program Income:Membership Dues:B 50 High-Fiver,14 Annual Membership - High-Fiver,1,50,50,50
406,"Shanna, Nancy & Mike",01/08/2015,Sales Receipt,1298,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,100
409,Big D Engineers,04/09/2015,Sales Receipt,1280,Special Events Income:Special Events Sponsors:...,NaN,1,250,250,250
412,"Harrington, Amelia",11/11/2013,Sales Receipt,1111,Program Income:Membership Dues:A 25 Acquaintance,14 Annual Membership - Acquaintance,1,25,25,25
415,Shiller Companies,08/28/2013,Sales Receipt,1005,Special Events Income:Special Events Sponsors:...,Title Sponsor,1,1000,1000,1000
418,"Hiscox, Christopher",09/10/2013,Sales Receipt,1014,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15
419,"Hiscox, Christopher",02/24/2015,Sales Receipt,1241,Special Events Income:The Great Escape,NaN,1,20,20,35
422,"Hoff, Suzanne",01/08/2015,Sales Receipt,1301,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
425,"Holiday, Eric & Marcy",05/21/14,Sales Receipt,1156,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
428,Hoot Owl,04/17/2015,Sales Receipt,1273,Direct Public Support:Corporate Contributions,Corporate Contributions,1,254,254,254
431,America,02/24/2015,Sales Receipt,1229,Special Events Income:The Great Escape,NaN,1,400,400,400
434,Margie Wilcox,11/20/2013,Sales Receipt,1104,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
437,Michael O'Dowd,10/30/2013,Sales Receipt,1073,Program Income:Membership Dues:C 75 Frienderton,Annual Membership - Frienderton,1,75,75,75
438,Michael O'Dowd,11/17/14,Sales Receipt,1292,Program Income:Membership Dues:C 75 Frienderton,Annual Membership - Frienderton,1,75,75,150
441,"Jack Donaghey, Inc.",10/03/14,Sales Receipt,1324,Special Events Income:Special Events Sponsors:...,Individual Sponsor,1,250,250,250
444,"Jarrell, Leah",10/22/2013,Sales Receipt,1033,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15
447,Jay M Carter,10/24/2013,Sales Receipt,1097,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,50

In [4]:
denote_company = set(['Network', 'LLC', 'LLP', 'Minnesota', 'Inc', 'INC', 'Bank', 'Engineers', 'Companies', 'Corporation','\'s', 'Quidditch', 'Plastics'])

In [5]:
mock_file['Title'] = ''
mock_file['First Name'] = ''
mock_file['Title'] = ''
mock_file['Middle Initial'] = ''
mock_file['Last Name'] = ''
mock_file['Suffix'] = ''
mock_file['Company'] = ''
mock_file['Salutation'] = ''



mock_file

,Name,Date,Transaction Type,Num,Product/Service,Memo/Description,Qty,Rate,Amount,Balance,Title,First Name,Middle Initial,Last Name,Suffix,Company,Salutation
1,Lethargy Network,11/07/2013,Sales Receipt,1100,Special Events Income:Special Events Contribut...,Special Events Contributions,1,635,635,635,,,,,,,
2,Lethargy Network,11/07/2013,Sales Receipt,1100,2016 Membership Dues,NaN,1,1,1,636,,,,,,,
5,"Adze, Anne & Spence",12/28/2013,Sales Receipt,1148,Program Income:Membership Dues:E 250 Old Friends,Annual Membership - Old Friends,1,250,250,250,,,,,,,
8,Minnesota Capital LLC,10/06/14,Sales Receipt,1334,Special Events Income:Special Events Sponsors:...,Osprey Sponsor,1,500,500,500,,,,,,,
11,Minnesota Coastal Heritage Trust,05/01/2015,Sales Receipt,1305,Direct Public Support:Corporate Contributions,Corporate Contributions,1,250,250,250,,,,,,,
14,"Ball, Lucille",02/24/2015,Sales Receipt,1179,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,
15,"Ball, Lucille",04/09/2015,Sales Receipt,1262,Special Events Income:Special Events Sponsors:...,NaN,1,40,40,65,,,,,,,
18,Lamar Odom,02/24/2015,Sales Receipt,1171,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,
21,"Andreas, Emily",10/28/2013,Sales Receipt,1086,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,
24,Andra Self Bruce,10/24/2013,Sales Receipt,1030,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15,,,,,,,
25,Andra Self Bruce,02/24/2015,Sales Receipt,1218,Special Events Income:The Great Escape,NaN,1,25,25,40,,,,,,,
28,Rick Rangel,05/21/2014,Sales Receipt,1162,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,
31,"Ambuehl Jackson, LLP",10/55/14,Sales Receipt,1338,Special Events Income:Special Events Sponsors:...,Silver Level Sponsor,1,250,250,250,,,,,,,
34,"Ambuehl, Conrad & Gigi",10/06/14,Sales Receipt,1333,Special Events Income:Special Events Sponsors:...,Individual Sponsor,1,250,250,250,,,,,,,
37,"Ash, Susan Jones",11/12/2013,Sales Receipt,1112,Program Income:Membership Dues:D 100 Friend,Annual Membership - Friend,1,100,100,100,,,,,,,
40,"asher, darryl",02/24/2015,Sales Receipt,1186,Special Events Income:The Great Escape,NaN,1,40,40,40,,,,,,,
43,"asher, James",02/24/2015,Sales Receipt,1247,Special Events Income:The Great Escape,NaN,1,20,20,20,,,,,,,
46,Barbara hayes,02/24/2015,Sales Receipt,1200,Special Events Income:The Great Escape,NaN,1,40,40,40,,,,,,,
49,"Barnett, David & Mary",10/28/2013,Sales Receipt,1144,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,
52,"Bell, Angela",02/24/2015,Sales Receipt,1225,Special Events Income:The Great Escape,NaN,1,40,40,40,,,,,,,
55,"Bender-Fayette, David L",04/17/2015,Sales Receipt,1285,Special Events Income:Special Events Sponsors:...,NaN,1,250,250,250,,,,,,,
58,"Bender-Fayette, Thomas & Dina",11/04/2013,Sales Receipt,1118,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,
61,"Bense, Leroy & Aurelia",11/13/2013,Sales Receipt,1165,Program Income:Membership Dues:B 50 High-Fiver,14 Annual Membership - High-Fiver,1,50,50,50,,,,,,,
64,Billy R Cyrus,12/28/2013,Sales Receipt,1152,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,
67,EKG & Co. INC.,10/03/14,Sales Receipt,1327,Special Events Income:Special Events Sponsors:...,Osprey Sponsor,1,500,500,500,,,,,,,
70,"Black, Peggy",02/24/2015,Sales Receipt,1213,Special Events Income:The Great Escape,NaN,1,20,20,20,,,,,,,
73,"Blackburn, James",10/19/2013,Sales Receipt,1044,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15,,,,,,,
76,"Blount, Russell",02/24/2015,Sales Receipt,1224,Special Events Income:The Great Escape,NaN,1,35,35,35,,,,,,,
79,Dockenstette,02/24/2015,Sales Receipt,1204,Special Events Income:The Great Escape,NaN,1,55,55,55,,,,,,,
82,"Bolson, Barry",01/08/2015,Sales Receipt,1299,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,"Raddick, Charlie & Corinne",10/21/14,Sales Receipt,1353,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,
373,"Grant, Bernadette",05/21/14,Sales Receipt,1155,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,
376,"Green, E Hamilton",10/25/2013,Sales Receipt,1062,Program Income:Membership Dues:D 100 Friend,14 Annual Membership - Friend,1,100,100,100,,,,,,,
377,"Green, E Hamilton",10/21/14,Sales Receipt,1296,Program Income:Membership Dues:D 100 Friend,Annual Membership - Friend,1,100,100,200,,,,,,,
380,Chuck M Yeager,10/22/2013,Sales Receipt,1037,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15,,,,,,,
381,Chuck M Yeager,10/26/2013,Sales Receipt,1053,Special Events Income:Special Events Contribut...,GC Entry Fee Day of Race Adult,1,20,20,35,,,,,,,
384,MinnesotaCoast Resource Cnservation & Develpme...,05/02/14,Sales Receipt,1004,Direct Public Grants:Foundations and Trusts,Trap the Trash Project,1,0,0,0,,,,,,,
387,"Backbarth Delivery Service, Inc.",10/06/14,Sales Receipt,1332,Special Events Income:Special Events Sponsors:...,River Otter Sponsor,1,1000,1000,1000,,,,,,,
390,"Shaefer, Susan & Jay",11/05/2013,Sales Receipt,1120,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,50,,,,,,,
393,"Shatner, Walter & Stephanie",01/08/2015,Sales Receipt,1304,Program Income:Membership Dues:C 75 Frienderton,Annual Membership - Frienderton,1,75,75,75,,,,,,,
396,"Famil, Jubal & Tray",11/17/14,Sales Receipt,1288,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,50,,,,,,,
399,Hancock Bank,10/06/14,Sales Receipt,1331,Special Events Income:Special Events Sponsors:...,Individual Sponsor,1,250,250,250,,,,,,,
402,"Hanley, Stewart",02/24/2015,Sales Receipt,1174,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,
405,"Shanna, Nancy & Mike",12/31/2013,Sales Receipt,1139,Program Income:Membership Dues:B 50 High-Fiver,14 Annual Membership - High-Fiver,1,50,50,50,,,,,,,
406,"Shanna, Nancy & Mike",01/08/2015,Sales Receipt,1298,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,100,,,,,,,
409,Big D Engineers,04/09/2015,Sales Receipt,1280,Special Events Income:Special Events Sponsors:...,NaN,1,250,250,250,,,,,,,
412,"Harrington, Amelia",11/11/2013,Sales Receipt,1111,Program Income:Membership Dues:A 25 Acquaintance,14 Annual Membership - Acquaintance,1,25,25,25,,,,,,,
415,Shiller Companies,08/28/2013,Sales Receipt,1005,Special Events Income:Special Events Sponsors:...,Title Sponsor,1,1000,1000,1000,,,,,,,
418,"Hiscox, Christopher",09/10/2013,Sales Receipt,1014,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15,,,,,,,
419,"Hiscox, Christopher",02/24/2015,Sales Receipt,1241,Special Events Income:The Great Escape,NaN,1,20,20,35,,,,,,,
422,"Hoff, Suzanne",01/08/2015,Sales Receipt,1301,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,
425,"Holiday, Eric & Marcy",05/21/14,Sales Receipt,1156,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,
428,Hoot Owl,04/17/2015,Sales Receipt,1273,Direct Public Support:Corporate Contributions,Corporate Contributions,1,254,254,254,,,,,,,
431,America,02/24/2015,Sales Receipt,1229,Special Events Income:The Great Escape,NaN,1,400,400,400,,,,,,,
434,Margie Wilcox,11/20/2013,Sales Receipt,1104,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,
437,Michael O'Dowd,10/30/2013,Sales Receipt,1073,Program Income:Membership Dues:C 75 Frienderton,Annual Membership - Frienderton,1,75,75,75,,,,,,,
438,Michael O'Dowd,11/17/14,Sales Receipt,1292,Program Income:Membership Dues:C 75 Frienderton,Annual Membership - Frienderton,1,75,75,150,,,,,,,
441,"Jack Donaghey, Inc.",10/03/14,Sales Receipt,1324,Special Events Income:Special Events Sponsors:...,Individual Sponsor,1,250,250,250,,,,,,,
444,"Jarrell, Leah",10/22/2013,Sales Receipt,1033,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15,,,,,,,
447,Jay M Carter,10/24/2013,Sales Receipt,1097,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,50,,,,,,,

In [6]:
mock_file = mock_file.to_dict()

In [7]:
def is_person_test(key):     # this function is to separate keys as 'raw' strings into company or name values
    if any(st in key for st in denote_company):
        return False
    else:
        return True

titles = set(['Dr', 'Dr.', 'Mr', 'Mr.', 'Ms', 'Ms.', 'Mrs', 'Mrs.', 'Sir', 'Dame'])
def title_test(x): # x is a list of strings
    if any(st in x for st in titles):
        return True
    else:
        return False


suffixes = set(['MD', 'PhD', 'Ph.D', 'Jr', 'Jr.'])
def suffix_test(x): #x is a list of strings
    if any(st in x for st in suffixes):
        return True
    else:
        return False

def two_humans_test(x): # x is a list of strings
    two_humans = ['&','and']
    if any(st in x for st in two_humans):
        return True
    else:
        return False
    
def surname_first_test(x): # x is a list of strings
    if ',' in x[0]:
        return True
    else: 
        return False


for value, key in mock_file['Name'].iteritems():
    if is_person_test(key) == True:
        company = None
        current_name = key.strip() #remove leading and trailing space/newline characters
        current_name = current_name.split(' ')  #split string into list of strings on spaces
        if title_test(current_name) == True:
            for i in current_name:
                if i in titles:
                    line_title = i               #save line_title for final output
            current_name = [x for x in current_name if x not in titles]
        else:
            line_title = None
        if suffix_test(current_name) == True:
            for i in current_name:
                if i in suffixes:
                    line_suffix = i               #save line_suffix for final output
            current_name = [x for x in current_name if x not in suffixes]
        else:
            line_suffix = None
        if surname_first_test(current_name) == True:
            lastname = current_name[0].strip(',') #save lastname for final output
            if two_humans_test(current_name) == True:
                firstname = current_name[1]+ ' '+current_name[2]+' '+current_name[3]
                if len(current_name) > 4:
                    middle_initial = current_name[4][0]
                else:
                    middle_initial = None
            else:
                firstname = current_name[1]
                if len(current_name)>2:
                    middle_initial = current_name[2]
                else: middle_initial = None
        if surname_first_test(current_name) == False:
            if len(current_name) == 3:
                firstname = current_name[0]
                middle_initial = current_name[1][0]
                lastname = current_name[2]
            if len(current_name) == 2:
                firstname = current_name[0]
                lastname = current_name[1]
                middle_initial = None
        salutation = 'Dear' 
        if line_title != None:
            salutation = salutation +' '+ line_title
        if firstname != None:
            salutation = salutation +' '+ firstname
        if middle_initial != None:
            salutation = salutation +' '+ middle_initial
        if lastname != None:
            salutation = salutation +' '+ lastname
        if line_suffix != None:
            salutation = salutation +' '+ line_suffix
            
    else: 
        line_title = None
        firstname = None
        middle_initial = None
        lastname = None
        line_suffix = None
        company = key
        salutation = 'Dear' + ' ' + company
    mock_file['Title'][value] = line_title
    mock_file['First Name'][value] = firstname
    mock_file['Middle Initial'][value] = middle_initial
    mock_file['Last Name'][value] = lastname
    mock_file['Suffix'][value] = line_suffix
    mock_file['Company'][value] = company
    mock_file['Salutation'][value] = salutation

In [8]:
data_frame = pd.DataFrame(mock_file)

In [9]:
data_frame

,Amount,Balance,Company,Date,First Name,Last Name,Memo/Description,Middle Initial,Name,Num,Product/Service,Qty,Rate,Salutation,Suffix,Title,Transaction Type
1,635,635,Lethargy Network,11/07/2013,None,None,Special Events Contributions,None,Lethargy Network,1100,Special Events Income:Special Events Contribut...,1,635,Dear Lethargy Network,None,None,Sales Receipt
2,1,636,Lethargy Network,11/07/2013,None,None,NaN,None,Lethargy Network,1100,2016 Membership Dues,1,1,Dear Lethargy Network,None,None,Sales Receipt
5,250,250,None,12/28/2013,Anne & Spence,Adze,Annual Membership - Old Friends,None,"Adze, Anne & Spence",1148,Program Income:Membership Dues:E 250 Old Friends,1,250,Dear Anne & Spence Adze,None,None,Sales Receipt
8,500,500,Minnesota Capital LLC,10/06/14,None,None,Osprey Sponsor,None,Minnesota Capital LLC,1334,Special Events Income:Special Events Sponsors:...,1,500,Dear Minnesota Capital LLC,None,None,Sales Receipt
11,250,250,Minnesota Coastal Heritage Trust,05/01/2015,None,None,Corporate Contributions,None,Minnesota Coastal Heritage Trust,1305,Direct Public Support:Corporate Contributions,1,250,Dear Minnesota Coastal Heritage Trust,None,None,Sales Receipt
14,25,25,None,02/24/2015,Lucille,Ball,Annual Membership - Acquaintance,None,"Ball, Lucille",1179,Program Income:Membership Dues:A 25 Acquaintance,1,25,Dear Lucille Ball,None,None,Sales Receipt
15,40,65,None,04/09/2015,Lucille,Ball,NaN,None,"Ball, Lucille",1262,Special Events Income:Special Events Sponsors:...,1,40,Dear Lucille Ball,None,None,Sales Receipt
18,25,25,None,02/24/2015,Lamar,Odom,Annual Membership - Acquaintance,None,Lamar Odom,1171,Program Income:Membership Dues:A 25 Acquaintance,1,25,Dear Lamar Odom,None,None,Sales Receipt
21,25,25,None,10/28/2013,Emily,Andreas,Annual Membership - Acquaintance,None,"Andreas, Emily",1086,Program Income:Membership Dues:A 25 Acquaintance,1,25,Dear Emily Andreas,None,None,Sales Receipt
24,15,15,None,10/24/2013,Andra,Bruce,GC Entry Fee Pre-Registered Adult,S,Andra Self Bruce,1030,Special Events Income:Special Events Contribut...,1,15,Dear Andra S Bruce,None,None,Sales Receipt
25,25,40,None,02/24/2015,Andra,Bruce,NaN,S,Andra Self Bruce,1218,Special Events Income:The Great Escape,1,25,Dear Andra S Bruce,None,None,Sales Receipt
28,25,25,None,05/21/2014,Rick,Rangel,Annual Membership - Acquaintance,None,Rick Rangel,1162,Program Income:Membership Dues:A 25 Acquaintance,1,25,Dear Rick Rangel,None,None,Sales Receipt
31,250,250,"Ambuehl Jackson, LLP",10/55/14,None,None,Silver Level Sponsor,None,"Ambuehl Jackson, LLP",1338,Special Events Income:Special Events Sponsors:...,1,250,"Dear Ambuehl Jackson, LLP",None,None,Sales Receipt
34,250,250,None,10/06/14,Conrad & Gigi,Ambuehl,Individual Sponsor,None,"Ambuehl, Conrad & Gigi",1333,Special Events Income:Special Events Sponsors:...,1,250,Dear Conrad & Gigi Ambuehl,None,None,Sales Receipt
37,100,100,None,11/12/2013,Susan,Ash,Annual Membership - Friend,Jones,"Ash, Susan Jones",1112,Program Income:Membership Dues:D 100 Friend,1,100,Dear Susan Jones Ash,None,None,Sales Receipt
40,40,40,None,02/24/2015,darryl,asher,NaN,None,"asher, darryl",1186,Special Events Income:The Great Escape,1,40,Dear darryl asher,None,None,Sales Receipt
43,20,20,None,02/24/2015,James,asher,NaN,None,"asher, James",1247,Special Events Income:The Great Escape,1,20,Dear James asher,None,None,Sales Receipt
46,40,40,None,02/24/2015,Barbara,hayes,NaN,None,Barbara hayes,1200,Special Events Income:The Great Escape,1,40,Dear Barbara hayes,None,None,Sales Receipt
49,25,25,None,10/28/2013,David & Mary,Barnett,Annual Membership - Acquaintance,None,"Barnett, David & Mary",1144,Program Income:Membership Dues:A 25 Acquaintance,1,25,Dear David & Mary Barnett,None,None,Sales Receipt
52,40,40,None,02/24/2015,Angela,Bell,NaN,None,"Bell, Angela",1225,Special Events Income:The Great Escape,1,40,Dear Angela Bell,None,None,Sales Receipt
55,250,250,None,04/17/2015,David,Bender-Fayette,NaN,L,"Bender-Fayette, David L",1285,Special Events Income:Special Events Sponsors:...,1,250,Dear David L Bender-Fayette,None,None,Sales Receipt
58,25,25,None,11/04/2013,Thomas & Dina,Bender-Fayette,Annual Membership - Acquaintance,None,"Bender-Fayette, Thomas & Dina",1118,Program Income:Membership Dues:A 25 Acquaintance,1,25,Dear Thomas & Dina Bender-Fayette,None,None,Sales Receipt
61,50,50,None,11/13/2013,Leroy & Aurelia,Bense,14 Annual Membership - High-Fiver,None,"Bense, Leroy & Aurelia",1165,Program Income:Membership Dues:B 50 High-Fiver,1,50,Dear Leroy & Aurelia Bense,None,None,Sales Receipt
64,25,25,None,12/28/2013,Billy,Cyrus,Annual Membership - Acquaintance,R,Billy R Cyrus,1152,Program Income:Membership Dues:A 25 Acquaintance,1,25,Dear Billy R Cyrus,None,None,Sales Receipt
67,500,500,EKG & Co. INC.,10/03/14,None,None,Osprey Sponsor,None,EKG & Co. INC.,1327,Special Events Income:Special Events Sponsors:...,1,500,Dear EKG & Co. INC.,None,None,Sales Receipt
70,20,20,None,02/24/2015,Peggy,Black,NaN,None,"Black, Peggy",1213,Special Events Income:The Great Escape,1,20,Dear Peggy Black,None,None,Sales Receipt
73,15,15,None,10/19/2013,James,Blackburn,GC Entry Fee Pre-Registered Adult,None,"Blackburn, James",1044,Special Events Income:Special Events Contribut...,1,15,Dear James Blackburn,None,None,Sales Receipt
76,35,35,None,02/24/2015,Russell,Blount,NaN,None,"Blount, Russell",1224,Special Events Income:The Great Escape,1,35,Dear Russell Blount,None,None,Sales Receipt
79,55,55,None,02/24/2015,Russell,Blount,NaN,None,Dockenstette,1204,Special Events Income:The Great Escape,1,55,Dear Russell Blount,None,None,Sales Receipt
82,25,25,None,01/08/2015,Barry,Bolson,Annual Membership - Acquaintance,None,"Bolson, Barry",1299,Program Income:Membership Dues:A 25 Acquaintance,1,25,Dear Barry Bolson,None,None,Sales Receipt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,25,25,None,10/21/14,Charlie & Corinne,Raddick,Annual Membership - Acquaintance,None,"Raddick, Charlie & Corinne",1353,Program Income:Membership Dues:A 25 Acquaintance,1,25,Dear Charlie & Corinne Raddick,None,None,Sales Receipt
373,25,25,None,05/21/14,Bernadette,Grant,Annual Membership - Acquaintance,None,"Grant, Bernadette",1155,Program Income:Membership Dues:A 25 Acquaintance,1,25,Dear Bernadette Grant,None,None,Sales Receipt
376,100,100,None,10/25/2013,E,Green,14 Annual Membership - Friend,Hamilton,"Green, E Hamilton",1062,Program Income:Membership Dues:D 100 Friend,1,100,Dear E Hamilton Green,None,None,Sales Receipt
377,100,200,None,10/21/14,E,Green,Annual Membership - Friend,Hamilton,"Green, E Hamilton",1296,Program Income:Membership Dues:D 100 Friend,1,100,Dear E Hamilton Green,None,None,Sales Receipt
380,15,15,None,10/22/2013,Chuck,Yeager,GC Entry Fee Pre-Registered Adult,M,Chuck M Yeager,1037,Special Events Income:Special Events Contribut...,1,15,Dear Chuck M Yeager,None,None,Sales Receipt
381,20,35,None,10/26/2013,Chuck,Yeager,GC Entry Fee Day of Race Adult,M,Chuck M Yeager,1053,Special Events Income:Special Events Contribut...,1,20,Dear Chuck M Yeager,None,None,Sales Receipt
384,0,0,MinnesotaCoast Resource Cnservation & Develpme...,05/02/14,None,None,Trap the Trash Project,None,MinnesotaCoast Resource Cnservation & Develpme...,1004,Direct Public Grants:Foundations and Trusts,1,0,Dear MinnesotaCoast Resource Cnservation & Dev...,None,None,Sales Receipt
387,1000,1000,"Backbarth Delivery Service, Inc.",10/06/14,None,None,River Otter Sponsor,None,"Backbarth Delivery Service, Inc.",1332,Special Events Income:Special Events Sponsors:...,1,1000,"Dear Backbarth Delivery Service, Inc.",None,None,Sales Receipt
390,50,50,None,11/05/2013,Susan & Jay,Shaefer,Annual Membership - High-Fiver,None,"Shaefer, Susan & Jay",1120,Program Income:Membership Dues:B 50 High-Fiver,1,50,Dear Susan & Jay Shaefer,None,None,Sales Receipt
393,75,75,None,01/08/2015,Walter & Stephanie,Shatner,Annual Membership - Frienderton,None,"Shatner, Walter & Stephanie",1304,Program Income:Membership Dues:C 75 Frienderton,1,75,Dear Walter & Stephanie Shatner,None,None,Sales Receipt
396,50,50,None,11/17/14,Jubal & Tray,Famil,Annual Membership - High-Fiver,None,"Famil, Jubal & Tray",1288,Program Income:Membership Dues:B 50 High-Fiver,1,50,Dear Jubal & Tray Famil,None,None,Sales Receipt
399,250,250,Hancock Bank,10/06/14,None,None,Individual Sponsor,None,Hancock Bank,1331,Special Events Income:Special Events Sponsors:...,1,250,Dear Hancock Bank,None,None,Sales Receipt
402,25,25,None,02/24/2015,Stewart,Hanley,Annual Membership - Acquaintance,None,"Hanley, Stewart",1174,Program Income:Membership Dues:A 25 Acquaintance,1,25,Dear Stewart Hanley,None,None,Sales Receipt
405,50,50,None,12/31/2013,Nancy & Mike,Shanna,14 Annual Membership - High-Fiver,None,"Shanna, Nancy & Mike",1139,Program Income:Membership Dues:B 50 High-Fiver,1,50,Dear Nancy & Mike Shanna,None,None,Sales Receipt
406,50,100,None,01/08/2015,Nancy & Mike,Shanna,Annual Membership - High-Fiver,None,"Shanna, Nancy & Mike",1298,Program Income:Membership Dues:B 50 High-Fiver,1,50,Dear Nancy & Mike Shanna,None,None,Sales Receipt
409,250,250,Big D Engineers,04/09/2015,None,None,NaN,None,Big D Engineers,1280,Special Events Income:Special Events Sponsors:...,1,250,Dear Big D Engineers,None,None,Sales Receipt
412,25,25,None,11/11/2013,Amelia,Harrington,14 Annual Membership - Acquaintance,None,"Harrington, Amelia",1111,Program Income:Membership Dues:A 25 Acquaintance,1,25,Dear Amelia Harrington,None,None,Sales Receipt
415,1000,1000,Shiller Companies,08/28/2013,None,None,Title Sponsor,None,Shiller Companies,1005,Special Events Income:Special Events Sponsors:...,1,1000,Dear Shiller Companies,None,None,Sales Receipt
418,15,15,None,09/10/2013,Christopher,Hiscox,GC Entry Fee Pre-Registered Adult,None,"Hiscox, Christopher",1014,Special Events Income:Special Events Contribut...,1,15,Dear Christopher Hiscox,None,None,Sales Receipt
419,20,35,None,02/24/2015,Christopher,Hiscox,NaN,None,"Hiscox, Christopher",1241,Special Events Income:The Great Escape,1,20,Dear Christopher Hiscox,None,None,Sales Receipt
422,25,25,None,01/08/2015,Suzanne,Hoff,Annual Membership - Acquaintance,None,"Hoff, Suzanne",1301,Program Income:Membership Dues:A 25 Acquaintance,1,25,Dear Suzanne Hoff,None,None,Sales Receipt
425,25,25,None,05/21/14,Eric & Marcy,Holiday,Annual Membership - Acquaintance,None,"Holiday, Eric & Marcy",1156,Program Income:Membership Dues:A 25 Acquaintance,1,25,Dear Eric & Marcy Holiday,None,None,Sales Receipt
428,254,254,None,04/17/2015,Hoot,Owl,Corporate Contributions,None,Hoot Owl,1273,Direct Public Support:Corporate Contributions,1,254,Dear Hoot Owl,None,None,Sales Receipt
431,400,400,None,02/24/2015,Hoot,Owl,NaN,None,America,1229,Special Events Income:The Great Escape,1,400,Dear Hoot Owl,None,None,Sales Receipt
434,25,25,None,11/20/2013,Margie,Wilcox,Annual Membership - Acquaintance,None,Margie Wilcox,1104,Program Income:Membership Dues:A 25 Acquaintance,1,25,Dear Margie Wilcox,None,None,Sales Receipt
437,75,75,None,10/30/2013,Michael,O'Dowd,Annual Membership - Frienderton,None,Michael O'Dowd,1073,Program Income:Membership Dues:C 75 Frienderton,1,75,Dear Michael O'Dowd,None,None,Sales Receipt
438,75,150,None,11/17/14,Michael,O'Dowd,Annual Membership - Frienderton,None,Michael O'Dowd,1292,Program Income:Membership Dues:C 75 Frienderton,1,75,Dear Michael O'Dowd,None,None,Sales Receipt
441,250,250,"Jack Donaghey, Inc.",10/03/14,None,None,Individual Sponsor,None,"Jack Donaghey, Inc.",1324,Special Events Income:Special Events Sponsors:...,1,250,"Dear Jack Donaghey, Inc.",None,None,Sales Receipt
444,15,15,None,10/22/2013,Leah,Jarrell,GC Entry Fee Pre-Registered Adult,None,"Jarrell, Leah",1033,Special Events Income:Special Events Contribut...,1,15,Dear Leah Jarrell,None,None,Sales Receipt
447,50,50,None,10/24/2013,Jay,Carter,Annual Membership - High-Fiver,M,Jay M Carter,1097,Program Income:Membership Dues:B 50 High-Fiver,1,50,Dear Jay M Carter,None,None,Sales Receipt

In [10]:
data_frame["Member ID"] = data_frame["Name"].astype("category") #Categories are new to me but so useful
data_frame['Member ID'] #this shows me there are 140 categories, which means 140 Members that need IDs

1                     Lethargy Network
2                     Lethargy Network
5                  Adze, Anne & Spence
8                Minnesota Capital LLC
11    Minnesota Coastal Heritage Trust
14                       Ball, Lucille
15                       Ball, Lucille
18                          Lamar Odom
21                      Andreas, Emily
24                    Andra Self Bruce
25                    Andra Self Bruce
28                         Rick Rangel
31                Ambuehl Jackson, LLP
34              Ambuehl, Conrad & Gigi
37                    Ash, Susan Jones
...
409          Big D Engineers
412       Harrington, Amelia
415        Shiller Companies
418      Hiscox, Christopher
419      Hiscox, Christopher
422            Hoff, Suzanne
425    Holiday, Eric & Marcy
428                 Hoot Owl
431                  America
434            Margie Wilcox
437           Michael O'Dowd
438           Michael O'Dowd
441      Jack Donaghey, Inc.
444            Jarrell, Leah
447             Jay M Carter
Name: Member ID, Length: 171, dtype: category
Categories (140, object): [America < Margie Wilcox < Michael O'Dowd < Adze, Anne & Spence ... asher, James < asher, darryl < curd, Danielle < doll, Danielle]

In [13]:
data_frame["Member ID"].cat.categories = range(1,141)  #I'm setting the categories to have a number from 1 to 141
data_frame = data_frame.drop_duplicates('Member ID')
data_frame = data_frame.set_index(data_frame['Member ID'])

In [14]:
Members_df = data_frame[['Title', 'First Name', 'Middle Initial', 'Last Name', 'Suffix', 'Company', 'Salutation']]

In [15]:
Members_df.to_csv('Members.csv') #Creates CSV File 1

1 120
2 120
5 4
8 121
11 122
14 12
15 12
18 119
21 8
24 7
25 7
28 128
31 5
34 6
37 9
40 138
43 137
46 13
49 14
52 15
55 16
58 17
61 18
64 20
67 78
70 21
73 22
76 23
79 68
82 24
85 25
88 31
91 32
94 30
97 26
100 27
103 28
104 28
107 29
110 127
113 126
114 126
117 129
120 99
123 100
126 101
127 101
130 33
133 34
136 35
139 118
142 38
143 38
146 39
149 40
150 40
153 37
154 37
157 36
160 41
163 42
166 43
169 44
172 45
175 46
176 46
179 47
182 49
185 50
188 51
191 52
192 52
195 53
198 75
199 74
202 112
205 113
208 54
211 55
212 55
215 139
218 106
219 106
222 56
225 57
228 58
231 107
232 107
235 59
238 60
241 62
242 62
245 63
248 134
251 135
254 136
257 64
260 61
263 65
266 108
267 108
268 108
271 66
274 67
277 140
280 69
283 70
284 70
285 70
288 71
289 71
292 72
293 72
294 72
297 73
298 73
301 76
304 88
305 88
308 77
311 80
314 79
317 81
320 83
323 84
324 84
327 124
328 124
331 85
334 86
337 93
340 87
343 90
346 89
349 91
352 92
355 94
358 95
361 96
364 97
367 11
370 125
373 98
376 102
377 102
380 48
381 48
384 123
387 10
390 130
393 132
396 82
399 103
402 104
405 131
406 131
409 19
412 105
415 133
418 109
419 109
422 110
425 111
428 114
431 1
434 2
437 3
438 3
441 115
444 116
447 117