In [24]:
import pandas as pd
import numpy

In [25]:
mock_file = pd.read_csv('sales by member detail 2013-2015 QB.csv')

In [26]:
mock_file = mock_file[mock_file.Num > 0]
mock_file

,Name,Date,Transaction Type,Num,Product/Service,Memo/Description,Qty,Rate,Amount,Balance
1,Lethargy Network,11/07/2013,Sales Receipt,1100,Special Events Income:Special Events Contribut...,Special Events Contributions,1,635,635,635
2,Lethargy Network,11/07/2013,Sales Receipt,1100,2016 Membership Dues,NaN,1,1,1,636
5,"Adze, Anne & Spence",12/28/2013,Sales Receipt,1148,Program Income:Membership Dues:E 250 Old Friends,Annual Membership - Old Friends,1,250,250,250
8,Minnesota Capital LLC,10/06/14,Sales Receipt,1334,Special Events Income:Special Events Sponsors:...,Osprey Sponsor,1,500,500,500
11,Minnesota Coastal Heritage Trust,05/01/2015,Sales Receipt,1305,Direct Public Support:Corporate Contributions,Corporate Contributions,1,250,250,250
14,"Ball, Lucille",02/24/2015,Sales Receipt,1179,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
15,"Ball, Lucille",04/09/2015,Sales Receipt,1262,Special Events Income:Special Events Sponsors:...,NaN,1,40,40,65
18,Lamar Odom,02/24/2015,Sales Receipt,1171,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
21,"Andreas, Emily",10/28/2013,Sales Receipt,1086,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
24,Andra Self Bruce,10/24/2013,Sales Receipt,1030,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15
25,Andra Self Bruce,02/24/2015,Sales Receipt,1218,Special Events Income:The Great Escape,NaN,1,25,25,40
28,Rick Rangel,05/21/2014,Sales Receipt,1162,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
31,"Ambuehl Jackson, LLP",10/55/14,Sales Receipt,1338,Special Events Income:Special Events Sponsors:...,Silver Level Sponsor,1,250,250,250
34,"Ambuehl, Conrad & Gigi",10/06/14,Sales Receipt,1333,Special Events Income:Special Events Sponsors:...,Individual Sponsor,1,250,250,250
37,"Ash, Susan Jones",11/12/2013,Sales Receipt,1112,Program Income:Membership Dues:D 100 Friend,Annual Membership - Friend,1,100,100,100
40,"asher, darryl",02/24/2015,Sales Receipt,1186,Special Events Income:The Great Escape,NaN,1,40,40,40
43,"asher, James",02/24/2015,Sales Receipt,1247,Special Events Income:The Great Escape,NaN,1,20,20,20
46,Barbara hayes,02/24/2015,Sales Receipt,1200,Special Events Income:The Great Escape,NaN,1,40,40,40
49,"Barnett, David & Mary",10/28/2013,Sales Receipt,1144,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
52,"Bell, Angela",02/24/2015,Sales Receipt,1225,Special Events Income:The Great Escape,NaN,1,40,40,40
55,"Bender-Fayette, David L",04/17/2015,Sales Receipt,1285,Special Events Income:Special Events Sponsors:...,NaN,1,250,250,250
58,"Bender-Fayette, Thomas & Dina",11/04/2013,Sales Receipt,1118,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
61,"Bense, Leroy & Aurelia",11/13/2013,Sales Receipt,1165,Program Income:Membership Dues:B 50 High-Fiver,14 Annual Membership - High-Fiver,1,50,50,50
64,Billy R Cyrus,12/28/2013,Sales Receipt,1152,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
67,EKG & Co. INC.,10/03/14,Sales Receipt,1327,Special Events Income:Special Events Sponsors:...,Osprey Sponsor,1,500,500,500
70,"Black, Peggy",02/24/2015,Sales Receipt,1213,Special Events Income:The Great Escape,NaN,1,20,20,20
73,"Blackburn, James",10/19/2013,Sales Receipt,1044,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15
76,"Blount, Russell",02/24/2015,Sales Receipt,1224,Special Events Income:The Great Escape,NaN,1,35,35,35
79,Dockenstette,02/24/2015,Sales Receipt,1204,Special Events Income:The Great Escape,NaN,1,55,55,55
82,"Bolson, Barry",01/08/2015,Sales Receipt,1299,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
...,...,...,...,...,...,...,...,...,...,...
370,"Raddick, Charlie & Corinne",10/21/14,Sales Receipt,1353,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
373,"Grant, Bernadette",05/21/14,Sales Receipt,1155,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
376,"Green, E Hamilton",10/25/2013,Sales Receipt,1062,Program Income:Membership Dues:D 100 Friend,14 Annual Membership - Friend,1,100,100,100
377,"Green, E Hamilton",10/21/14,Sales Receipt,1296,Program Income:Membership Dues:D 100 Friend,Annual Membership - Friend,1,100,100,200
380,Chuck M Yeager,10/22/2013,Sales Receipt,1037,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15
381,Chuck M Yeager,10/26/2013,Sales Receipt,1053,Special Events Income:Special Events Contribut...,GC Entry Fee Day of Race Adult,1,20,20,35
384,MinnesotaCoast Resource Cnservation & Develpme...,05/02/14,Sales Receipt,1004,Direct Public Grants:Foundations and Trusts,Trap the Trash Project,1,0,0,0
387,"Backbarth Delivery Service, Inc.",10/06/14,Sales Receipt,1332,Special Events Income:Special Events Sponsors:...,River Otter Sponsor,1,1000,1000,1000
390,"Shaefer, Susan & Jay",11/05/2013,Sales Receipt,1120,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,50
393,"Shatner, Walter & Stephanie",01/08/2015,Sales Receipt,1304,Program Income:Membership Dues:C 75 Frienderton,Annual Membership - Frienderton,1,75,75,75
396,"Famil, Jubal & Tray",11/17/14,Sales Receipt,1288,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,50
399,Hancock Bank,10/06/14,Sales Receipt,1331,Special Events Income:Special Events Sponsors:...,Individual Sponsor,1,250,250,250
402,"Hanley, Stewart",02/24/2015,Sales Receipt,1174,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
405,"Shanna, Nancy & Mike",12/31/2013,Sales Receipt,1139,Program Income:Membership Dues:B 50 High-Fiver,14 Annual Membership - High-Fiver,1,50,50,50
406,"Shanna, Nancy & Mike",01/08/2015,Sales Receipt,1298,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,100
409,Big D Engineers,04/09/2015,Sales Receipt,1280,Special Events Income:Special Events Sponsors:...,NaN,1,250,250,250
412,"Harrington, Amelia",11/11/2013,Sales Receipt,1111,Program Income:Membership Dues:A 25 Acquaintance,14 Annual Membership - Acquaintance,1,25,25,25
415,Shiller Companies,08/28/2013,Sales Receipt,1005,Special Events Income:Special Events Sponsors:...,Title Sponsor,1,1000,1000,1000
418,"Hiscox, Christopher",09/10/2013,Sales Receipt,1014,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15
419,"Hiscox, Christopher",02/24/2015,Sales Receipt,1241,Special Events Income:The Great Escape,NaN,1,20,20,35
422,"Hoff, Suzanne",01/08/2015,Sales Receipt,1301,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
425,"Holiday, Eric & Marcy",05/21/14,Sales Receipt,1156,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
428,Hoot Owl,04/17/2015,Sales Receipt,1273,Direct Public Support:Corporate Contributions,Corporate Contributions,1,254,254,254
431,America,02/24/2015,Sales Receipt,1229,Special Events Income:The Great Escape,NaN,1,400,400,400
434,Margie Wilcox,11/20/2013,Sales Receipt,1104,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25
437,Michael O'Dowd,10/30/2013,Sales Receipt,1073,Program Income:Membership Dues:C 75 Frienderton,Annual Membership - Frienderton,1,75,75,75
438,Michael O'Dowd,11/17/14,Sales Receipt,1292,Program Income:Membership Dues:C 75 Frienderton,Annual Membership - Frienderton,1,75,75,150
441,"Jack Donaghey, Inc.",10/03/14,Sales Receipt,1324,Special Events Income:Special Events Sponsors:...,Individual Sponsor,1,250,250,250
444,"Jarrell, Leah",10/22/2013,Sales Receipt,1033,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15
447,Jay M Carter,10/24/2013,Sales Receipt,1097,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,50

In [27]:
denote_company = set(['Network', 'LLC', 'LLP', 'Minnesota', 'Inc', 'INC', 'Bank', 'Engineers', 'Companies', 'Corporation','\'s', 'Quidditch', 'Plastics'])

In [28]:
mock_file['Title'] = ''
mock_file['First Name'] = ''
mock_file['Title'] = ''
mock_file['Middle Initial'] = ''
mock_file['Last Name'] = ''
mock_file['Suffix'] = ''
mock_file['Company'] = ''
mock_file['Salutation'] = ''
mock_file['Category'] = ''
mock_file['Sub-Category'] = ''
mock_file['Item'] = ''



mock_file

,Name,Date,Transaction Type,Num,Product/Service,Memo/Description,Qty,Rate,Amount,Balance,Title,First Name,Middle Initial,Last Name,Suffix,Company,Salutation,Category,Sub-Category,Item
1,Lethargy Network,11/07/2013,Sales Receipt,1100,Special Events Income:Special Events Contribut...,Special Events Contributions,1,635,635,635,,,,,,,,,,
2,Lethargy Network,11/07/2013,Sales Receipt,1100,2016 Membership Dues,NaN,1,1,1,636,,,,,,,,,,
5,"Adze, Anne & Spence",12/28/2013,Sales Receipt,1148,Program Income:Membership Dues:E 250 Old Friends,Annual Membership - Old Friends,1,250,250,250,,,,,,,,,,
8,Minnesota Capital LLC,10/06/14,Sales Receipt,1334,Special Events Income:Special Events Sponsors:...,Osprey Sponsor,1,500,500,500,,,,,,,,,,
11,Minnesota Coastal Heritage Trust,05/01/2015,Sales Receipt,1305,Direct Public Support:Corporate Contributions,Corporate Contributions,1,250,250,250,,,,,,,,,,
14,"Ball, Lucille",02/24/2015,Sales Receipt,1179,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,,,,
15,"Ball, Lucille",04/09/2015,Sales Receipt,1262,Special Events Income:Special Events Sponsors:...,NaN,1,40,40,65,,,,,,,,,,
18,Lamar Odom,02/24/2015,Sales Receipt,1171,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,,,,
21,"Andreas, Emily",10/28/2013,Sales Receipt,1086,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,,,,
24,Andra Self Bruce,10/24/2013,Sales Receipt,1030,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15,,,,,,,,,,
25,Andra Self Bruce,02/24/2015,Sales Receipt,1218,Special Events Income:The Great Escape,NaN,1,25,25,40,,,,,,,,,,
28,Rick Rangel,05/21/2014,Sales Receipt,1162,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,,,,
31,"Ambuehl Jackson, LLP",10/55/14,Sales Receipt,1338,Special Events Income:Special Events Sponsors:...,Silver Level Sponsor,1,250,250,250,,,,,,,,,,
34,"Ambuehl, Conrad & Gigi",10/06/14,Sales Receipt,1333,Special Events Income:Special Events Sponsors:...,Individual Sponsor,1,250,250,250,,,,,,,,,,
37,"Ash, Susan Jones",11/12/2013,Sales Receipt,1112,Program Income:Membership Dues:D 100 Friend,Annual Membership - Friend,1,100,100,100,,,,,,,,,,
40,"asher, darryl",02/24/2015,Sales Receipt,1186,Special Events Income:The Great Escape,NaN,1,40,40,40,,,,,,,,,,
43,"asher, James",02/24/2015,Sales Receipt,1247,Special Events Income:The Great Escape,NaN,1,20,20,20,,,,,,,,,,
46,Barbara hayes,02/24/2015,Sales Receipt,1200,Special Events Income:The Great Escape,NaN,1,40,40,40,,,,,,,,,,
49,"Barnett, David & Mary",10/28/2013,Sales Receipt,1144,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,,,,
52,"Bell, Angela",02/24/2015,Sales Receipt,1225,Special Events Income:The Great Escape,NaN,1,40,40,40,,,,,,,,,,
55,"Bender-Fayette, David L",04/17/2015,Sales Receipt,1285,Special Events Income:Special Events Sponsors:...,NaN,1,250,250,250,,,,,,,,,,
58,"Bender-Fayette, Thomas & Dina",11/04/2013,Sales Receipt,1118,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,,,,
61,"Bense, Leroy & Aurelia",11/13/2013,Sales Receipt,1165,Program Income:Membership Dues:B 50 High-Fiver,14 Annual Membership - High-Fiver,1,50,50,50,,,,,,,,,,
64,Billy R Cyrus,12/28/2013,Sales Receipt,1152,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,,,,
67,EKG & Co. INC.,10/03/14,Sales Receipt,1327,Special Events Income:Special Events Sponsors:...,Osprey Sponsor,1,500,500,500,,,,,,,,,,
70,"Black, Peggy",02/24/2015,Sales Receipt,1213,Special Events Income:The Great Escape,NaN,1,20,20,20,,,,,,,,,,
73,"Blackburn, James",10/19/2013,Sales Receipt,1044,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15,,,,,,,,,,
76,"Blount, Russell",02/24/2015,Sales Receipt,1224,Special Events Income:The Great Escape,NaN,1,35,35,35,,,,,,,,,,
79,Dockenstette,02/24/2015,Sales Receipt,1204,Special Events Income:The Great Escape,NaN,1,55,55,55,,,,,,,,,,
82,"Bolson, Barry",01/08/2015,Sales Receipt,1299,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,"Raddick, Charlie & Corinne",10/21/14,Sales Receipt,1353,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,,,,
373,"Grant, Bernadette",05/21/14,Sales Receipt,1155,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,,,,
376,"Green, E Hamilton",10/25/2013,Sales Receipt,1062,Program Income:Membership Dues:D 100 Friend,14 Annual Membership - Friend,1,100,100,100,,,,,,,,,,
377,"Green, E Hamilton",10/21/14,Sales Receipt,1296,Program Income:Membership Dues:D 100 Friend,Annual Membership - Friend,1,100,100,200,,,,,,,,,,
380,Chuck M Yeager,10/22/2013,Sales Receipt,1037,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15,,,,,,,,,,
381,Chuck M Yeager,10/26/2013,Sales Receipt,1053,Special Events Income:Special Events Contribut...,GC Entry Fee Day of Race Adult,1,20,20,35,,,,,,,,,,
384,MinnesotaCoast Resource Cnservation & Develpme...,05/02/14,Sales Receipt,1004,Direct Public Grants:Foundations and Trusts,Trap the Trash Project,1,0,0,0,,,,,,,,,,
387,"Backbarth Delivery Service, Inc.",10/06/14,Sales Receipt,1332,Special Events Income:Special Events Sponsors:...,River Otter Sponsor,1,1000,1000,1000,,,,,,,,,,
390,"Shaefer, Susan & Jay",11/05/2013,Sales Receipt,1120,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,50,,,,,,,,,,
393,"Shatner, Walter & Stephanie",01/08/2015,Sales Receipt,1304,Program Income:Membership Dues:C 75 Frienderton,Annual Membership - Frienderton,1,75,75,75,,,,,,,,,,
396,"Famil, Jubal & Tray",11/17/14,Sales Receipt,1288,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,50,,,,,,,,,,
399,Hancock Bank,10/06/14,Sales Receipt,1331,Special Events Income:Special Events Sponsors:...,Individual Sponsor,1,250,250,250,,,,,,,,,,
402,"Hanley, Stewart",02/24/2015,Sales Receipt,1174,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,,,,
405,"Shanna, Nancy & Mike",12/31/2013,Sales Receipt,1139,Program Income:Membership Dues:B 50 High-Fiver,14 Annual Membership - High-Fiver,1,50,50,50,,,,,,,,,,
406,"Shanna, Nancy & Mike",01/08/2015,Sales Receipt,1298,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,100,,,,,,,,,,
409,Big D Engineers,04/09/2015,Sales Receipt,1280,Special Events Income:Special Events Sponsors:...,NaN,1,250,250,250,,,,,,,,,,
412,"Harrington, Amelia",11/11/2013,Sales Receipt,1111,Program Income:Membership Dues:A 25 Acquaintance,14 Annual Membership - Acquaintance,1,25,25,25,,,,,,,,,,
415,Shiller Companies,08/28/2013,Sales Receipt,1005,Special Events Income:Special Events Sponsors:...,Title Sponsor,1,1000,1000,1000,,,,,,,,,,
418,"Hiscox, Christopher",09/10/2013,Sales Receipt,1014,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15,,,,,,,,,,
419,"Hiscox, Christopher",02/24/2015,Sales Receipt,1241,Special Events Income:The Great Escape,NaN,1,20,20,35,,,,,,,,,,
422,"Hoff, Suzanne",01/08/2015,Sales Receipt,1301,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,,,,
425,"Holiday, Eric & Marcy",05/21/14,Sales Receipt,1156,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,,,,
428,Hoot Owl,04/17/2015,Sales Receipt,1273,Direct Public Support:Corporate Contributions,Corporate Contributions,1,254,254,254,,,,,,,,,,
431,America,02/24/2015,Sales Receipt,1229,Special Events Income:The Great Escape,NaN,1,400,400,400,,,,,,,,,,
434,Margie Wilcox,11/20/2013,Sales Receipt,1104,Program Income:Membership Dues:A 25 Acquaintance,Annual Membership - Acquaintance,1,25,25,25,,,,,,,,,,
437,Michael O'Dowd,10/30/2013,Sales Receipt,1073,Program Income:Membership Dues:C 75 Frienderton,Annual Membership - Frienderton,1,75,75,75,,,,,,,,,,
438,Michael O'Dowd,11/17/14,Sales Receipt,1292,Program Income:Membership Dues:C 75 Frienderton,Annual Membership - Frienderton,1,75,75,150,,,,,,,,,,
441,"Jack Donaghey, Inc.",10/03/14,Sales Receipt,1324,Special Events Income:Special Events Sponsors:...,Individual Sponsor,1,250,250,250,,,,,,,,,,
444,"Jarrell, Leah",10/22/2013,Sales Receipt,1033,Special Events Income:Special Events Contribut...,GC Entry Fee Pre-Registered Adult,1,15,15,15,,,,,,,,,,
447,Jay M Carter,10/24/2013,Sales Receipt,1097,Program Income:Membership Dues:B 50 High-Fiver,Annual Membership - High-Fiver,1,50,50,50,,,,,,,,,,

In [29]:
mock_file = mock_file.to_dict()

In [30]:
def is_person_test(key):     # this function is to separate keys as 'raw' strings into company or name values
    if any(st in key for st in denote_company):
        return False
    else:
        return True

titles = set(['Dr', 'Dr.', 'Mr', 'Mr.', 'Ms', 'Ms.', 'Mrs', 'Mrs.', 'Sir', 'Dame'])
def title_test(x): # x is a list of strings
    if any(st in x for st in titles):
        return True
    else:
        return False


suffixes = set(['MD', 'PhD', 'Ph.D', 'Jr', 'Jr.'])
def suffix_test(x): #x is a list of strings
    if any(st in x for st in suffixes):
        return True
    else:
        return False

def two_humans_test(x): # x is a list of strings
    two_humans = ['&','and']
    if any(st in x for st in two_humans):
        return True
    else:
        return False
    
def surname_first_test(x): # x is a list of strings
    if ',' in x[0]:
        return True
    else: 
        return False


for value, key in mock_file['Name'].iteritems():
    if is_person_test(key) == True:
        company = None
        current_name = key.strip() #remove leading and trailing space/newline characters
        current_name = current_name.split(' ')  #split string into list of strings on spaces
        if title_test(current_name) == True:
            for i in current_name:
                if i in titles:
                    line_title = i               #save line_title for final output
            current_name = [x for x in current_name if x not in titles]
        else:
            line_title = None
        if suffix_test(current_name) == True:
            for i in current_name:
                if i in suffixes:
                    line_suffix = i               #save line_suffix for final output
            current_name = [x for x in current_name if x not in suffixes]
        else:
            line_suffix = None
        if surname_first_test(current_name) == True:
            lastname = current_name[0].strip(',') #save lastname for final output
            if two_humans_test(current_name) == True:
                firstname = current_name[1]+ ' '+current_name[2]+' '+current_name[3]
                if len(current_name) > 4:
                    middle_initial = current_name[4][0]
                else:
                    middle_initial = None
            else:
                firstname = current_name[1]
                if len(current_name)>2:
                    middle_initial = current_name[2]
                else: middle_initial = None
        if surname_first_test(current_name) == False:
            if len(current_name) == 3:
                firstname = current_name[0]
                middle_initial = current_name[1][0]
                lastname = current_name[2]
            if len(current_name) == 2:
                firstname = current_name[0]
                lastname = current_name[1]
                middle_initial = None
        salutation = 'Dear' 
        if line_title != None:
            salutation = salutation +' '+ line_title
        if firstname != None:
            salutation = salutation +' '+ firstname
        if middle_initial != None:
            salutation = salutation +' '+ middle_initial
        if lastname != None:
            salutation = salutation +' '+ lastname
        if line_suffix != None:
            salutation = salutation +' '+ line_suffix
            
    else: 
        line_title = None
        firstname = None
        middle_initial = None
        lastname = None
        line_suffix = None
        company = key
        salutation = 'Dear' + ' ' + company
    mock_file['Title'][value] = line_title
    mock_file['First Name'][value] = firstname
    mock_file['Middle Initial'][value] = middle_initial
    mock_file['Last Name'][value] = lastname
    mock_file['Suffix'][value] = line_suffix
    mock_file['Company'][value] = company
    mock_file['Salutation'][value] = salutation
    
for key, value in mock_file['Product/Service'].iteritems():
    contents = value.split(':')
    if len(contents) == 1:
        category = None
        sub_category = None
        item = contents
    if len(contents) == 2:
        category = contents[0]
        sub_category = None
        item = contents[1]
    if len(contents) == 3:
        category = contents[0]
        sub_category = contents[1]
        item = contents [2]
    mock_file['Category'][key] = category
    mock_file['Sub-Category'][key] = sub_category
    mock_file['Item'][key] = item

In [31]:
data_frame = pd.DataFrame(mock_file)

In [32]:
data_frame["Member ID"] = data_frame["Name"].astype("category") #Categories are new to me but so useful
data_frame['Member ID'] #this shows me there are 140 categories, which means 140 Members that need IDs

1                     Lethargy Network
2                     Lethargy Network
5                  Adze, Anne & Spence
8                Minnesota Capital LLC
11    Minnesota Coastal Heritage Trust
14                       Ball, Lucille
15                       Ball, Lucille
18                          Lamar Odom
21                      Andreas, Emily
24                    Andra Self Bruce
25                    Andra Self Bruce
28                         Rick Rangel
31                Ambuehl Jackson, LLP
34              Ambuehl, Conrad & Gigi
37                    Ash, Susan Jones
...
409          Big D Engineers
412       Harrington, Amelia
415        Shiller Companies
418      Hiscox, Christopher
419      Hiscox, Christopher
422            Hoff, Suzanne
425    Holiday, Eric & Marcy
428                 Hoot Owl
431                  America
434            Margie Wilcox
437           Michael O'Dowd
438           Michael O'Dowd
441      Jack Donaghey, Inc.
444            Jarrell, Leah
447             Jay M Carter
Name: Member ID, Length: 171, dtype: category
Categories (140, object): [America < Margie Wilcox < Michael O'Dowd < Adze, Anne & Spence ... asher, James < asher, darryl < curd, Danielle < doll, Danielle]

In [33]:
data_frame["Member ID"].cat.categories = range(1,141)  #I'm setting the categories to have a number from 1 to 141
data_frame = data_frame.set_index(data_frame['Member ID'])

In [34]:
Members_df = data_frame[['Title', 'First Name', 'Middle Initial', 'Last Name', 'Suffix', 'Company', 'Salutation']]
Members_df = Members_df.drop_duplicates()

In [15]:
Members_df.to_csv('Members.csv') #Creates CSV File 1

In [38]:
Donations_df = data_frame[['Date', 'Num', 'Rate', 'Category', 'Sub-Category', 'Item', 'Memo/Description']]
Donations_df.columns = ['Transaction Date', 'Transaction Number', 'Amount', 'Category','Sub-Category', 'Item', 'Description']

In [40]:
Donations_df.to_csv('Donations.csv') # Creates CSV File 2